Feature/Database and Authentication
augisbud/PROPRO pull request #7
Opened 2023-12-12 20:30 UTC by augisbud

Install Docker Desktop

`docker run -d --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=supersecret postgres`

`dotnet ef database update`

2023-12-14 13:50 UTC, Edvinas11 requested changes
Need to do CORS settings

2023-12-15 12:47 UTC, Edvinas11 requested changes

2023-12-15 12:47 UTC, Edvinas11 commented on InvoicesBackend/Program.cs
You can add these lines here
`builder.Services.AddCors(options => {
    options.AddPolicy("AllowSpecificOrigin", builder => {
        builder.AllowAnyOrigin();
        builder.AllowAnyMethod();
        builder.AllowAnyHeader();
    });
});`

2023-12-15 12:47 UTC, Edvinas11 commented on InvoicesBackend/Program.cs
Add additional line here: `app.UseCors("AllowSpecificOrigin");`

2023-12-15 13:14 UTC, Edvinas11 commented on InvoicesBackend/Controllers/LoginController.cs
> +            return Ok(token);
Should return a JSON format token `return Ok(new { token });`

2023-12-19 09:33 UTC, augisbud commented on InvoicesBackend/Controllers/LoginController.cs
> +            return Ok(token);
Addressed in https://github.com/augisbud/PROPRO/pull/7/commits/8eda1b360955d00f8a7b355ce4aa394c12489b26

2023-12-19 09:33 UTC, augisbud commented on InvoicesBackend/Program.cs
Addressed in https://github.com/augisbud/PROPRO/pull/7/commits/8eda1b360955d00f8a7b355ce4aa394c12489b26

2023-12-19 09:33 UTC, augisbud commented on InvoicesBackend/Program.cs
Addressed in https://github.com/augisbud/PROPRO/pull/7/commits/8eda1b360955d00f8a7b355ce4aa394c12489b26

2023-12-19 10:21 UTC, Edvinas11 approved these changes

2023-12-19 10:21 UTC, merged